# Generated by Django 5.0.6 on 2024-07-10 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_jobaddress_jobpostphoto_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(default='no title', max_length=100),
        ),
    ]
