# Generated by Django 5.0.6 on 2024-07-10 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_job_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='payement_choice',
            field=models.CharField(choices=[('PerHour', 'PerHour'), ('PerDay', 'PerDay'), ('PerWeek', 'PerWeek'), ('PerMonth', 'PerMonth'), ('PerTask', 'PerTask')], default='PerTask', max_length=20),
        ),
    ]
