# Generated by Django 5.0.6 on 2024-07-10 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_job_payement_choice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='job_adress',
            new_name='job_address',
        ),
    ]
