# Generated by Django 5.0.6 on 2024-07-08 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_employer',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_worker',
        ),
        migrations.AddField(
            model_name='customuser',
            name='account_type',
            field=models.CharField(choices=[('Worker', 'Worker'), ('Employer', 'Employer'), ('Admin', 'Admin')], default='Worker', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
        migrations.AlterField(
            model_name='workerprofile',
            name='prefered_job_categories',
            field=models.ManyToManyField(related_name='job_categories', to='jobs.jobcategory'),
        ),
    ]
